services:

    activity_db:
      image: postgres:alpine
      env_file:
        - .env
      environment:
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_ACTIVITY}
        POSTGRES_USER: ${POSTGRES_USER_ACTIVITY}
        POSTGRES_DB: ${POSTGRES_DB_ACTIVITY}
      expose:
        - 5432
    
    activity_ms:
      restart: always
      env_file: 
        - .env
      environment:
        DATABASE_URI_ACTIVITY: ${DATABASE_URI_ACTIVITY}
        ACTIVITY_LOCALHOST: ${ACTIVITY_LOCALHOST}
        SECRET_KEY: ${SECRET_KEY}
        ALGORITHM: ${ALGORITHM}
        ACCESS_TOKEN_EXPIRE_MINUTES: ${ACCESS_TOKEN_EXPIRE_MINUTES}
        AUTH_URL: ${AUTH_URL}
      build: ../activity
      command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
      ports:
        - 8003:8000
      depends_on:
        - activity_db