services:
  publications:
    restart: always
    env_file:
      - .env
    environment:
      ENVIRONMENT: ${ENVIRONMENT}

      DATABASE_URI_LOCAL: ${DATABASE_URI_LOCAL}

      DSN_SENTRY_USERS: ${DSN_SENTRY}

      API_KEY_FIREBASE: ${API_KEY_FIREBASE}
      AUTH_DOMAIN_FIREBASE: ${AUTH_DOMAIN_FIREBASE}
      PROJECT_ID_FIREBASE: ${PROJECT_ID_FIREBASE}
      STORAGE_BUCKET_FIREBASE: ${STORAGE_BUCKET_FIREBASE}
      MESSAGING_SENDER_ID_FIREBASE: ${MESSAGING_SENDER_ID_FIREBASE}
      APP_ID_FIREBASE: ${APP_ID_FIREBASE}
      DATABASE_URL_FIREBASE: ${DATABASE_URL_FIREBASE}

      SECRET_KEY: ${SECRET_KEY}
      ALGORITHM: ${ALGORITHM}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${ACCESS_TOKEN_EXPIRE_MINUTES}

      AUTH_URL: ${AUTH_URL}

    build:
        context: .
        dockerfile: Dockerfile
    ports:
      - 8002:8080
