name: Production CI

on:
  push:
    branches:
      - main

jobs:
  build-unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create .env file
        run: echo "${{ secrets.ENV_FILE_CONTENT }}" > .env

      - name: Generate Image Tag
        id: tag
        run: echo "::set-output name=tag::$(git log --pretty=format:'%h' -n 1)"

      - name: Build Docker Compose
        run: |
          docker compose up --build -d 
      
      - name: Wait for container to be healthy
        run: |
          until [ "$(docker inspect -f '{{.State.Health.Status}}' publications)" == "healthy" ]; do
            echo "Waiting for container to be healthy..."
            sleep 5
          done
             
      - name: Run tests
        run: |
          CONTAINER_ID=$(docker ps --filter "name=publications" --filter "status=running" --format "{{.ID}}")
          if [ -z "$CONTAINER_ID" ]; then
            echo "Container is not running. Exiting..."
            exit 1
          fi
            docker exec $CONTAINER_ID sh -c "cd /src && pytest -vv --tb=long"
        
