name: Production CI

on:
  push:
    branches:
      - main

jobs:
  build-unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create .env file
        run: echo "${{ secrets.ENV_FILE_CONTENT }}" > .env

      - name: Generate Image Tag
        id: tag
        run: echo "::set-output name=tag::$(git log --pretty=format:'%h' -n 1)"

      - name: Build Docker Compose
        run: |
          docker compose up --build -d      
      - name: Wait for services to be ready
        run: sleep 10
      
      - name: Run pytest inside container
        run: |
          CONTAINER_ID=$(docker ps --filter "name=publications" --format "{{.ID}}")
          docker exec $CONTAINER_ID sh -c "cd /src && pytest -vv --tb=long"
